[2022-05-12 07:39:45,506] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data manual__2022-05-12T07:39:44.969752+00:00 [queued]>
[2022-05-12 07:39:45,514] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data manual__2022-05-12T07:39:44.969752+00:00 [queued]>
[2022-05-12 07:39:45,515] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:39:45,516] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-12 07:39:45,517] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-12 07:39:45,533] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stop_producer_twitter_data> on 2022-05-12 07:39:44.969752+00:00
[2022-05-12 07:39:45,540] {standard_task_runner.py:52} INFO - Started process 375 to run task
[2022-05-12 07:39:45,546] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stop_live_stream_Dag', 'stop_producer_twitter_data', 'manual__2022-05-12T07:39:44.969752+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/stop_live_stream_dags.py', '--cfg-path', '/tmp/tmpz__9t8oo', '--error-file', '/tmp/tmphgtws0kb']
[2022-05-12 07:39:45,548] {standard_task_runner.py:80} INFO - Job 3: Subtask stop_producer_twitter_data
[2022-05-12 07:39:45,610] {task_command.py:369} INFO - Running <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data manual__2022-05-12T07:39:44.969752+00:00 [running]> on host c5e465c36164
[2022-05-12 07:39:45,708] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=stop_live_stream_Dag
AIRFLOW_CTX_TASK_ID=stop_producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T07:39:44.969752+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-12T07:39:44.969752+00:00
[2022-05-12 07:39:45,712] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-12 07:39:45,715] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 -f /opt/***/dags/producer_tweets.py']
[2022-05-12 07:39:45,725] {subprocess.py:85} INFO - Output:
[2022-05-12 07:39:45,731] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-12 07:39:45,911] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-12 07:39:45,916] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stop_live_stream_Dag, task_id=stop_producer_twitter_data, execution_date=20220512T073944, start_date=20220512T073945, end_date=20220512T073945
[2022-05-12 07:39:46,031] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task stop_producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 375)
[2022-05-12 07:39:46,081] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-12 07:39:46,110] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
