[2022-05-16 10:02:38,546] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Collect_Data_Dag.get_data_src_age_category_weather_wise scheduled__2022-05-14T18:00:00+00:00 [queued]>
[2022-05-16 10:02:38,556] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Collect_Data_Dag.get_data_src_age_category_weather_wise scheduled__2022-05-14T18:00:00+00:00 [queued]>
[2022-05-16 10:02:38,557] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:02:38,558] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-16 10:02:38,560] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:02:38,572] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_data_src_age_category_weather_wise> on 2022-05-14 18:00:00+00:00
[2022-05-16 10:02:38,578] {standard_task_runner.py:52} INFO - Started process 1226 to run task
[2022-05-16 10:02:38,581] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Collect_Data_Dag', 'get_data_src_age_category_weather_wise', 'scheduled__2022-05-14T18:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/collect_data_dag.py', '--cfg-path', '/tmp/tmp3jvjc1g3', '--error-file', '/tmp/tmple9x_w6v']
[2022-05-16 10:02:38,583] {standard_task_runner.py:80} INFO - Job 164: Subtask get_data_src_age_category_weather_wise
[2022-05-16 10:02:38,637] {task_command.py:369} INFO - Running <TaskInstance: Collect_Data_Dag.get_data_src_age_category_weather_wise scheduled__2022-05-14T18:00:00+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:02:38,806] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=Collect_Data_Dag
AIRFLOW_CTX_TASK_ID=get_data_src_age_category_weather_wise
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T18:00:00+00:00
[2022-05-16 10:02:38,808] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:02:38,809] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/scripts/dag_data_source_api_9.py']
[2022-05-16 10:02:38,818] {subprocess.py:85} INFO - Output:
[2022-05-16 10:02:48,710] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-16 10:02:48,714] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 1226. PIDs of all processes in the group: [1227, 1226]
[2022-05-16 10:02:48,716] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 1226
[2022-05-16 10:02:48,718] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-16 10:02:48,719] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-16 10:02:48,775] {process_utils.py:75} INFO - Process psutil.Process(pid=1226, status='terminated', exitcode=0, started='10:02:37') (1226) terminated with exit code 0
[2022-05-16 10:02:48,776] {process_utils.py:75} INFO - Process psutil.Process(pid=1227, status='terminated', started='10:02:37') (1227) terminated with exit code None
