[2022-05-16 10:01:13,425] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Collect_Data_Dag.get_data_src_impacted_country_week_wise scheduled__2022-05-14T18:00:00+00:00 [queued]>
[2022-05-16 10:01:13,433] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: Collect_Data_Dag.get_data_src_impacted_country_week_wise scheduled__2022-05-14T18:00:00+00:00 [queued]>
[2022-05-16 10:01:13,435] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:01:13,436] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-16 10:01:13,437] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:01:13,448] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): get_data_src_impacted_country_week_wise> on 2022-05-14 18:00:00+00:00
[2022-05-16 10:01:13,452] {standard_task_runner.py:52} INFO - Started process 559 to run task
[2022-05-16 10:01:13,455] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'Collect_Data_Dag', 'get_data_src_impacted_country_week_wise', 'scheduled__2022-05-14T18:00:00+00:00', '--job-id', '163', '--raw', '--subdir', 'DAGS_FOLDER/collect_data_dag.py', '--cfg-path', '/tmp/tmp08gs0nb0', '--error-file', '/tmp/tmphtuaqd_d']
[2022-05-16 10:01:13,456] {standard_task_runner.py:80} INFO - Job 163: Subtask get_data_src_impacted_country_week_wise
[2022-05-16 10:01:13,540] {task_command.py:369} INFO - Running <TaskInstance: Collect_Data_Dag.get_data_src_impacted_country_week_wise scheduled__2022-05-14T18:00:00+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:01:13,818] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=Collect_Data_Dag
AIRFLOW_CTX_TASK_ID=get_data_src_impacted_country_week_wise
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T18:00:00+00:00
[2022-05-16 10:01:13,819] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:01:13,821] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/scripts/dag_data_source_api_7.py']
[2022-05-16 10:01:13,832] {subprocess.py:85} INFO - Output:
[2022-05-16 10:02:39,560] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
[2022-05-16 10:02:39,564] {process_utils.py:129} INFO - Sending Signals.SIGTERM to group 559. PIDs of all processes in the group: [562, 559]
[2022-05-16 10:02:39,566] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 559
[2022-05-16 10:02:39,568] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2022-05-16 10:02:39,569] {subprocess.py:103} INFO - Sending SIGTERM signal to process group
[2022-05-16 10:02:39,659] {process_utils.py:75} INFO - Process psutil.Process(pid=562, status='terminated', started='10:01:12') (562) terminated with exit code None
[2022-05-16 10:02:39,661] {process_utils.py:75} INFO - Process psutil.Process(pid=559, status='terminated', exitcode=0, started='10:01:12') (559) terminated with exit code 0
