[2022-05-16 10:05:34,421] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-16T10:05:26.886598+00:00 [queued]>
[2022-05-16 10:05:34,428] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-16T10:05:26.886598+00:00 [queued]>
[2022-05-16 10:05:34,430] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:05:34,433] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-05-16 10:05:34,434] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:05:34,446] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-16 10:05:26.886598+00:00
[2022-05-16 10:05:34,450] {standard_task_runner.py:52} INFO - Started process 2690 to run task
[2022-05-16 10:05:34,455] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'manual__2022-05-16T10:05:26.886598+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpjmhzzar7', '--error-file', '/tmp/tmpwq5oth_8']
[2022-05-16 10:05:34,457] {standard_task_runner.py:80} INFO - Job 167: Subtask producer_twitter_data
[2022-05-16 10:05:34,507] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data manual__2022-05-16T10:05:26.886598+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:05:34,702] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-16T10:05:26.886598+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-05-16T10:05:26.886598+00:00
[2022-05-16 10:05:34,704] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:05:34,705] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/scripts/producer_tweets.py']
[2022-05-16 10:05:34,713] {subprocess.py:85} INFO - Output:
[2022-05-16 10:05:35,116] {subprocess.py:92} INFO - Traceback (most recent call last):
[2022-05-16 10:05:35,117] {subprocess.py:92} INFO -   File "/opt/***/dags/scripts/producer_tweets.py", line 21, in <module>
[2022-05-16 10:05:35,118] {subprocess.py:92} INFO -     producer = KafkaProducer(bootstrap_servers='localhost:9093')
[2022-05-16 10:05:35,118] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/producer/kafka.py", line 383, in __init__
[2022-05-16 10:05:35,120] {subprocess.py:92} INFO -     **self.config)
[2022-05-16 10:05:35,121] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 244, in __init__
[2022-05-16 10:05:35,122] {subprocess.py:92} INFO -     self.config['api_version'] = self.check_version(timeout=check_timeout)
[2022-05-16 10:05:35,123] {subprocess.py:92} INFO -   File "/home/***/.local/lib/python3.7/site-packages/kafka/client_async.py", line 900, in check_version
[2022-05-16 10:05:35,124] {subprocess.py:92} INFO -     raise Errors.NoBrokersAvailable()
[2022-05-16 10:05:35,125] {subprocess.py:92} INFO - kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2022-05-16 10:05:35,143] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-16 10:05:35,161] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-16 10:05:35,166] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220516T100526, start_date=20220516T100534, end_date=20220516T100535
[2022-05-16 10:05:35,176] {standard_task_runner.py:97} ERROR - Failed to execute job 167 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 2690)
[2022-05-16 10:05:35,192] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-16 10:05:35,232] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
