[2022-05-16 10:00:53,063] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data scheduled__2022-05-12T18:00:00+00:00 [queued]>
[2022-05-16 10:00:53,087] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data scheduled__2022-05-12T18:00:00+00:00 [queued]>
[2022-05-16 10:00:53,091] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:00:53,092] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-16 10:00:53,093] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:00:53,132] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): stop_producer_twitter_data> on 2022-05-12 18:00:00+00:00
[2022-05-16 10:00:53,146] {standard_task_runner.py:52} INFO - Started process 203 to run task
[2022-05-16 10:00:53,244] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'stop_live_stream_Dag', 'stop_producer_twitter_data', 'scheduled__2022-05-12T18:00:00+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/stop_live_stream_dags.py', '--cfg-path', '/tmp/tmp3y5qecnq', '--error-file', '/tmp/tmp89zau_c7']
[2022-05-16 10:00:53,275] {standard_task_runner.py:80} INFO - Job 148: Subtask stop_producer_twitter_data
[2022-05-16 10:00:53,542] {task_command.py:369} INFO - Running <TaskInstance: stop_live_stream_Dag.stop_producer_twitter_data scheduled__2022-05-12T18:00:00+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:00:54,428] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=stop_live_stream_Dag
AIRFLOW_CTX_TASK_ID=stop_producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-12T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-12T18:00:00+00:00
[2022-05-16 10:00:54,431] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:00:54,434] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'pkill -9 -f /opt/***/dags/scripts/producer_tweets.py']
[2022-05-16 10:00:54,519] {subprocess.py:85} INFO - Output:
[2022-05-16 10:00:54,606] {subprocess.py:96} INFO - Command exited with return code 1
[2022-05-16 10:00:55,438] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-05-16 10:00:55,445] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=stop_live_stream_Dag, task_id=stop_producer_twitter_data, execution_date=20220512T180000, start_date=20220516T100053, end_date=20220516T100055
[2022-05-16 10:00:55,490] {standard_task_runner.py:97} ERROR - Failed to execute job 148 for task stop_producer_twitter_data (Bash command failed. The command returned a non-zero exit code 1.; 203)
[2022-05-16 10:00:55,638] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-16 10:00:55,806] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
