[2022-05-16 10:00:53,193] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data scheduled__2022-05-14T18:00:00+00:00 [queued]>
[2022-05-16 10:00:53,251] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: live_stream_Dag.producer_twitter_data scheduled__2022-05-14T18:00:00+00:00 [queued]>
[2022-05-16 10:00:53,253] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:00:53,255] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-05-16 10:00:53,257] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 10:00:53,336] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): producer_twitter_data> on 2022-05-14 18:00:00+00:00
[2022-05-16 10:00:53,356] {standard_task_runner.py:52} INFO - Started process 210 to run task
[2022-05-16 10:00:53,381] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'live_stream_Dag', 'producer_twitter_data', 'scheduled__2022-05-14T18:00:00+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/live_stream_dag.py', '--cfg-path', '/tmp/tmpg22m4jez', '--error-file', '/tmp/tmpngeg3cwk']
[2022-05-16 10:00:53,387] {standard_task_runner.py:80} INFO - Job 153: Subtask producer_twitter_data
[2022-05-16 10:00:53,766] {task_command.py:369} INFO - Running <TaskInstance: live_stream_Dag.producer_twitter_data scheduled__2022-05-14T18:00:00+00:00 [running]> on host 6c2369487cbf
[2022-05-16 10:00:54,809] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Airflow
AIRFLOW_CTX_DAG_ID=live_stream_Dag
AIRFLOW_CTX_TASK_ID=producer_twitter_data
AIRFLOW_CTX_EXECUTION_DATE=2022-05-14T18:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-14T18:00:00+00:00
[2022-05-16 10:00:54,823] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-05-16 10:00:54,833] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/dags/scripts/producer_tweets.py']
[2022-05-16 10:00:54,944] {subprocess.py:85} INFO - Output:
[2022-05-16 10:00:55,311] {subprocess.py:96} INFO - Command exited with return code -9
[2022-05-16 10:00:55,436] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code -9.
[2022-05-16 10:00:55,448] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=live_stream_Dag, task_id=producer_twitter_data, execution_date=20220514T180000, start_date=20220516T100053, end_date=20220516T100055
[2022-05-16 10:00:55,520] {standard_task_runner.py:97} ERROR - Failed to execute job 153 for task producer_twitter_data (Bash command failed. The command returned a non-zero exit code -9.; 210)
[2022-05-16 10:00:55,651] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-16 10:00:55,805] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
